"""removed name from FTE

Revision ID: 354289e64ae3
Revises: 40677b4946ca
Create Date: 2023-11-06 15:17:12.436894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354289e64ae3'
down_revision = '40677b4946ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
