"""added hourly wages

Revision ID: 365a643d5acc
Revises: d4f69a52f9d1
Create Date: 2023-10-31 13:38:33.625715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365a643d5acc'
down_revision = 'd4f69a52f9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_wages', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.drop_column('hourly_wages')

    # ### end Alembic commands ###
