"""added name to foodtruckevent

Revision ID: 40677b4946ca
Revises: c2d3b2c17447
Create Date: 2023-11-06 14:31:21.831466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40677b4946ca'
down_revision = 'c2d3b2c17447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
