"""empty message

Revision ID: 98d7ba5a0e9a
Revises: d4f69a52f9d1
Create Date: 2023-10-31 19:35:38.642399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d7ba5a0e9a'
down_revision = 'd4f69a52f9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_wages', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_truck_event_table', schema=None) as batch_op:
        batch_op.drop_column('hourly_wages')

    # ### end Alembic commands ###
