"""empty message

Revision ID: c2d3b2c17447
Revises: 365a643d5acc
Create Date: 2023-11-02 16:06:59.878626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2d3b2c17447'
down_revision = '365a643d5acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_event_table_user_id_user_table'), 'user_table', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_table_user_id_user_table'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
